name: jehn
favicon: null
layout_spectrum: 0.5118383790832013
typography_spectrum: 0.3592670888174325
title: Gettting started with AI webbuilding
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.47113371710292995
  lightness: 0.5794255947694182
  saturation: 0.10822495236061513
  rhythmicContrast: 0.2818492229562253
purpose: []
